use Mix.Config

config :zix, ZixWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :zix, Zix.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "zix_dev",
  hostname: "localhost",
  pool_size: 10

config :zix, ZixWeb.Guardian,
  allowed_algos: ["ES512"],
  secret_key: %{
    "alg" => "ES512",
    "crv" => "P-521",
    "d" => "AXRSCyICUQ7bWmC7BYrudxPGgtCRaPnIVvNWMD30cuhFFwku0DICJ3KiMC7lZ0JBXKzK3Rj1to8WA2wBZraQ3IYL",
    "kty" => "EC",
    "use" => "sig",
    "x" => "AO5YOC7Pu9DeREGpI49Cv4aO3R605vIkrZnXIQx_g_1qsLUt7ZBBmlVbIpGu3pjmrTLtiobFiooi41ijvL7VoLOT",
    "y" => "AKmsYBOmNJT2PkeLBzryoVC1lzjHNLkicWGGzSPGCjJkZNEEdq6K4_I7wiYM26kDLEaYwyLbrZen7qvBBDoJ6732"
  }
